//login
export const FETCH_USER = "FETCH_LOGIN";
export const FETCH_USER_ERROR = "FETCH_LOGIN_ERROR";
export const FETCH_USER_SUCCESS = "FETCH_LOGIN_SUCCESS";
//sign in
export const FETCH_SIGN_IN = "FETCH_SIGN_IN";
export const FETCH_SIGN_IN_ERROR = "FETCH_SIGN_IN_ERROR";
export const FETCH_SIGN_IN_SUCCESS = "FETCH_SIGN_IN_SUCCESS";
